name: Go
on: [push]
jobs:

  default:
    name: Default CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVersion: ["1.10", "1.11", "1.12", "1.13"]
    steps:

    - name: Set up Go ${{ matrix.goVersion }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.goVersion }}
      id: go

    - name: Check out code into the GOPATH
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/cvgw/gocheckcov

    - name: Install dep and golangci-lint then ensure vendor
      env:
        GOPATH: /home/runner/work/gocheckcov/go
      run: |
        export PATH=$PATH:$GOPATH/bin

        sudo apt-get install -y go-dep
        which dep
        dep ensure
        # Install golangci-lint
        curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0

    - name: Make default
      env:
        GOPATH: /home/runner/work/gocheckcov/go
      run: |
        export PATH=$PATH:$GOPATH/bin

        make
